### ISSUE TITLE
DialogExtendedProgressBar.xml

### ISSUE THREAD

**Issue by blaher23** [JezzX/skin.pm3-hd#1]
Thanks for this skin.  It's still the best for XBMC.  The latest Frodo RC3 gives this error in the log:

ERROR: unable to load:C:\Users\UserName\AppData\Roaming\XBMC\addons\skin.pm3-hd-master\720p\DialogExtendedProgressBar.xml, Line 0
                                            Failed to open file

**Comment by JezzX** [comment]
yeah I know the skin has no frodo support yet its on my todo list
